### ISSUE TITLE
BUG: Failed to compile. Missing LittleFS.h

### ISSUE THREAD

**Issue by ulises2k** [mobizt/ESP-Google-Sheet-Client#12]
**Describe the bug**
When compiling the readme example, using a "Raspberry Pi Pico", I get an error that the library "LittleFS.h" is missing.

**To Reproduce**
Compile the example Readmin.md

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2415609/219967658-aca12e70-473c-4ac5-94bb-ac83cf99f5da.png)

**IDE and its version:**
 - Arduino 2.0.3

**Raspberry Pi Pico**

**Comment by mobizt** [comment]
This library required this SDK instead of embed SDK.
https://github.com/mobizt/ESP-Google-Sheet-Client#rp2040-arduino-sdk-installation
