### ISSUE TITLE
undefined reference to `tokenStatusCallback(gauth_token_info_t)'

### ISSUE THREAD

**Issue by MaximeM** [mobizt/ESP-Google-Sheet-Client#32]
Hello there,

I have no idea has to why this is not working, I implemented the example as showed.

I am on an esp32 and using platformIO

`c:/users/maxim/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: .pio\build\nodemcu-32s\src\main.cpp.o:(.literal._Z5setupv+0x10c): undefined reference to `tokenStatusCallback(gauth_token_info_t)'`

**Comment by mobizt** [comment]
You should create the callback prototype function above the setup as in the examples.

**Comment by mobizt** [comment]
You should create the callback prototype function above the setup as in the examples.

**Comment by mobizt** [comment]
This is prototype function.
https://github.com/mobizt/ESP-Google-Sheet-Client/blob/6fd89411138f8e312a3fb1efeb1ad07ff87ce8d5/examples/Values/Append/Append.ino#L86

This is the real function.
https://github.com/mobizt/ESP-Google-Sheet-Client/blob/6fd89411138f8e312a3fb1efeb1ad07ff87ce8d5/examples/Values/Append/Append.ino#L194-L205
