### ISSUE TITLE
Something wrong in range syntax

### ISSUE THREAD

**Issue by DrWino** [mobizt/ESP-Google-Sheet-Client#6]
First of all - thanks for an excellent tutorial. I was amazed how far I got. I set up the API and I was able to list, create and write Google sheets. Just wonderful - would never have got this far on my own.

Here is my problem:
If I specify the spreadsheet as dataFilters1.add("a1Range","Sheet1!A1:A2")  I get error:  

"message": "Unable to parse range: Sheet1!B1:B3",

However if I change it to "A1:A2" I can read and write to the spreadsheet. What gives here ?

**Comment by mobizt** [comment]
You should read the Google documentation as this library was built based on Google APIs.

**Comment by mobizt** [comment]
You should read the REST API related to [these functions](https://github.com/mobizt/ESP-Google-Sheet-Client#functions-description).

**Comment by mobizt** [comment]
The range format is right if your sheet title is "Sheet1".

**Comment by mobizt** [comment]
The range format is right if your sheet title is "Sheet1".

**Comment by DrWino** [comment]
You are right - it was in front of my face - Sheet was labelled New Sheet. I guess I was used to excel where the default is Sheet1. Renamed New Sheet to Sheet1 and all is well. Great contribution and great support.
